# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rubygems-yoink"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dave Benvenuti"]
  s.date = "2013-03-04"
  s.description = "rubygems plugin which will allow a no-yank sync from a rubygems mirror"
  s.email = "davebenvenuti@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/rubygems-yoink.rb",
    "lib/rubygems_plugin.rb",
    "lib/yoink/command.rb",
    "lib/yoink/gem_set.rb",
    "rubygems-yoink.gemspec",
    "test/fixtures/vcr/gem_set/test_can_load_from_mirror.yml",
    "test/helper.rb",
    "test/test-redis.conf",
    "test/unit/yoink/command_test.rb",
    "test/unit/yoink/gem_set_test.rb"
  ]
  s.homepage = "http://github.com/yoink/rubygems-yoink"
  s.licenses = ["ASLv2"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "rubygems plugin which will allow a no-yank sync from a rubygems mirror"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubygems-mirror>, [">= 0"])
      s.add_runtime_dependency(%q<redis>, [">= 0"])
      s.add_runtime_dependency(%q<connection_pool>, [">= 0"])
      s.add_runtime_dependency(%q<fog>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rubygems-mirror>, [">= 0"])
      s.add_dependency(%q<redis>, [">= 0"])
      s.add_dependency(%q<connection_pool>, [">= 0"])
      s.add_dependency(%q<fog>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rubygems-mirror>, [">= 0"])
    s.add_dependency(%q<redis>, [">= 0"])
    s.add_dependency(%q<connection_pool>, [">= 0"])
    s.add_dependency(%q<fog>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

